[tool.poetry]
name = "obsidian-rag"
version = "0.1.0"
description = ""
authors = ["anpigon <markan82@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.2.2"
langchainhub = "^0.1.17"
langchain_chroma = "^0.1.1"
langchain-community = "^0.2.3"
langchain_text_splitters = "^0.2.1"
sentence_transformers = "^3.0.0"
chromadb = "^0.5.0"
gradio = "^4.33.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
